############################################################
# Configuration of external libraries -- not all are needed
############################################################
# RootFind

# Which platform
#MAC_OS_X = 1
MAC_OS_X = 0

# math package
#set the following item to zero if GSL is not present
HAVE_GSL=0
#set the following 3 items to zero if CLAPACK is not present
HAVE_CLAPACK=1
HAVE_LAPACK=1
HAVE_BLAS=1
CLAPACK_DIR = $(HOME)/CLAPACK
MATH_DEFINES += HAVE_GSL=$(HAVE_GSL) HAVE_CLAPACK=$(HAVE_CLAPACK) HAVE_LAPACK=$(HAVE_LAPACK) HAVE_BLAS=$(HAVE_BLAS)
ifeq ($(HAVE_CLAPACK),1)
  MATH_INCDIR += $(CLAPACK_DIR) $(CLAPACK_DIR)/F2CLIBS $(CLAPACK_DIR)/BLAS/WRAP
endif
ifeq ($(HAVE_GSL),1)
  MATH_INCDIR += $(GSL_DIR)
endif

## For Mac, use HAVE_IEEE_COMPARISONS
# comment out the following line if isinf,isnan,finite are not defined
# on your system
#MATH_DEFINES+= HAVE_DECL_ISINF HAVE_DECL_ISNAN HAVE_DECL_FINITE
# uncomment the following if you want to use IEEE comparisons to test
# nan,inf,finite numbers
MATH_DEFINES+= HAVE_IEEE_COMPARISONS

